### ISSUE TITLE
ios7 crash

### ISSUE THREAD

**Issue by zziking** [forkingdog/FDStackView#14]
device: iPhone 4 iOS 7.1.2
step: add->remove->add

Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to install constraint on view.  Does the constraint reference something from outside the subtree of the view?  That's illegal. constraint:<NSLayoutConstraint:0x16df7cb0 'FDSV-spacing' H:[UILabel:0x16df05c0]-(0)-[UILabel:0x16d52d40]> view:<UIStackView: 0x16ded770; frame = (0 0; 320 100); autoresize = RM+BM; layer = <FDTransformLayer: 0x16ded9b0>>'

**Comment by xcly01** [comment]
int main(int, char **) [Line 18]main Exception:Could not instantiate class named UIStackView 一样崩溃了。

**Comment by sunnyxx** [comment]
Fixed, thanks
