### ISSUE TITLE
 在AutoLayout布局下的疑问

### ISSUE THREAD

**Issue by ValiantCat** [forkingdog/FDStackView#16]
CAlayer 层是不支持AutoLayout   一般用Frame 或者bounds  来计算大小  但是Autolayout布局确定的时机不对 如何读出正确的frame    ViewController  有个 -viewDidLayoutSubviewS 方法  

那么问题来了 View怎么读?

**Comment by wtlucky** [comment]
你可以试试layoutSubviews这个方法，不过这个问题并不是UIStackView/FDStackView的问题，你可以去StackOverflow提问这个问题。

**Comment by ValiantCat** [comment]
这个方法并没有什么卵用  stackOVerFlow  也没有人回答   只是觉得这个作者 可能会遇见这个问题  请教一下
