### ISSUE TITLE
Storyboard Reference 可以类似这个支持IOS7以上版本吗？

### ISSUE THREAD

**Issue by maplelover** [forkingdog/FDStackView#18]
Storyboard Reference 也是IOS9才支持，如果低版本也能用就好了

**Comment by wtlucky** [comment]
并不能

**Comment by mokai** [comment]
确实并不能，Storyboard Reference相对的类是UIStoryboardViewControllerPlaceholder，但并没有公开，在链接时会报
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_UIStoryboardViewControllerPlaceholder", referenced from:
