### ISSUE TITLE
iOS 8.3/8.4 phone5/5s/5c 卡顿严重，排渣找到了原因

### ISSUE THREAD

**Issue by JasonXin** [forkingdog/FDStackView#19]
- (void)intrinsicContentSizeInvalidatedForChildView:(UIView *)childView {
  [self.distributionArrangement intrinsicContentSizeInvalidatedForItem:childView];
  [self.alignmentArrangement intrinsicContentSizeInvalidatedForItem:childView];
  }
  上面这个更新布局的方法，在iOS7 不会调用，iOS8 会疯狂的调用，会导致界面卡顿很严重，然后注释掉这段代码卡顿消失，界面也没用什么影响，想问下，这个方法的作用？

**Comment by wtlucky** [comment]
这个方法的作用是当StackView的子视图的intrinsicContentSize需要更新时，系统调用的方法，比如一个Label的text更改时。

**Comment by JasonXin** [comment]
为什么ios7 不会调用，8 会频繁的调用，导致卡顿严重呢？

**Comment by lordyangtze** [comment]
这里确实会有问题，方法名很明确指出需要无效化传进去的childView的intrinsicSize，但是方法全程并没有用到childView而是对整个stackView重新布局了，以至于只要stackView有一些小改动，整个stackView都要跟着刷新，如果stackView里有两个childView需要更新，根据代码逻辑，刷新就会调用两次，这损耗非常大

**Comment by sunnyxx** [comment]
我们将会在下一个版本对这个问题进行优化，谢谢各位
