### ISSUE TITLE
释放的时候kvo crash了。。。。iOS8.1模拟器

### ISSUE THREAD

**Issue by jl322137** [forkingdog/FDStackView#3]
2015-10-09 18:14:45.803 Qingwen[74545:2004789] **\* Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <UIStackView 0x7fb183c8d350> for the key path "hidden" from <UIStackView 0x7fb183c99490> because it is not registered as an observer.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001074b7f35 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000107124bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x00000001074b7e6d +[NSException raise:format:] + 205
    3   Foundation                          0x0000000104375609 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 608
    4   Foundation                          0x000000010437530c -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 90
    5   Qingwen                             0x0000000102ec018b -[FDStackView removeHiddenObserverForView:] + 91
    6   Qingwen                             0x0000000102ebf8e5 -[FDStackView removeArrangedSubview:] + 421
    7   Qingwen                             0x0000000102ebf6fe -[FDStackView willRemoveSubview:] + 62
    8   UIKit                               0x000000010526649c __UIViewWillBeRemovedFromSuperview + 142
    9   UIKit                               0x00000001052661c9 -[UIView(Hierarchy) removeFromSuperview] + 91
    10  UIKit                               0x0000000105259e39 -[UIView dealloc] + 404
    11  Qingwen                             0x0000000102ec04af -[FDStackView dealloc] + 223
    12  CoreFoundation                      0x000000010738f78b CFRelease + 603
    13  CoreFoundation                      0x00000001073a30bd -[__NSArrayM dealloc] + 157
    14  libobjc.A.dylib                     0x000000010713928e _ZN11objc_object17sidetable_releaseEb + 236
    15  libobjc.A.dylib                     0x00000001071398cd _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 591
    16  CoreFoundation                      0x00000001073aeda6 _CFAutoreleasePoolPop + 22
    17  CoreFoundation                      0x00000001073e2ef3 __CFRunLoopRun + 2051
    18  CoreFoundation                      0x00000001073e2486 CFRunLoopRunSpecific + 470
    19  GraphicsServices                    0x000000010a31c9f0 GSEventRunModal + 161
    20  UIKit                               0x00000001051fb420 UIApplicationMain + 1282
    21  Qingwen                             0x0000000102ea4e0f main + 111
    22  libdyld.dylib                       0x00000001081ce145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by sunnyxx** [comment]
已经修复，谢谢
