### ISSUE TITLE
pod方式安装后，ios8 alloc后stackview为nil

### ISSUE THREAD

**Issue by guoweikun621** [forkingdog/FDStackView#38]

**Comment by ghost** [comment]
Have same issue here. 
Already set `Builder for 9.0 and later` in `Interface Builder Document`

**Comment by guoweikun621** [comment]
已经在xib设置为9.0及以后了，alloc后还是会为nil。但是如果直接把FDStackView源文件拖入工程，而不用pod安装，alloc后就正常了。难道是不支持pod方式？

**Comment by ghost** [comment]
@guoweikun621 我按照你的方法拖入工程，然后 copy 例子代码 执行，发现`UIStackView *stackView = [[UIStackView alloc] init];`依然是nil。难道是我遗漏了什么步骤？

**Comment by guoweikun621** [comment]
@stoneimoimoi 我用是sb做的，直接代码alloc我没试过。在sb上，如果FDStackView是pod安装的就不行，copy到工程就可以。

**Comment by ghost** [comment]
谢谢。。。我已经改用 OAStackView了。。。

**Comment by wtlucky** [comment]
#36

**Comment by wtlucky** [comment]
The same issue as #36

**Comment by guakeliao** [comment]
@ghost 
ios 9 之前用：
       UIStackView *stackView = [[NSClassFromString(@"UIStackView") alloc]init];
