### ISSUE TITLE
How did you automatically replace the symbol for UIStackView into FDStackView at runtime before iOS9.

### ISSUE THREAD

**Issue by SeanChense** [forkingdog/FDStackView#4]
Please tell me.

**Comment by sunnyxx** [comment]
See `FDStackViewPatchEntry` function and assembles in the bottom of `FDStackView.m`,  here's some explanations about how to locate symbol and replace it: https://gist.github.com/OliverLetterer/4643294  
And we may post a blog in Chinese talking about it in detail.

**Comment by SeanChense** [comment]
Looking forward to your good blog :)
