### ISSUE TITLE
Use with swift

### ISSUE THREAD

**Issue by Alex293** [forkingdog/FDStackView#43]
Hi,

I'd like to use this lib with swift 3. I've added the files directly to my project (I need to use dynamic frameworks so no cocoapod with this one). Then I've added a bridging header so it seems that all is good. My issue is the availability, Xcode require me to use availability to check if sdk is > 9.

I've added the customs flags to disable compatibility check as in #2 

The issue is I use compatibility for other things like notifications so I can't really disable it. Is there a way to disable it for only a particular place in the code ?

**Comment by lizhihui0215** [comment]
`let stackView = UIStackView()` crash anybody help me
