### ISSUE TITLE
使用Reveal查看结构导致Reveal 崩溃

### ISSUE THREAD

**Issue by xiaomaogong** [forkingdog/FDStackView#9]
发现你们的例子里面如果使用Reveal查看层次结构会导致Reveal崩溃，是否能解决这一问题？

**Comment by wtlucky** [comment]
你用的是什么版本的系统和Reveal呢？ 1.5.1版本的Reveal还不支持iOS9. 现在Reveal release了1.6.0版本。应该没有问题了。

**Comment by xiaomaogong** [comment]
刚试了一下，确实跟你说的一样，升到最新的Reveal问题就解决了
